### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by robocrotic** [shahthepro/dex#1]
Hi, Im trying to put this together. I have a local private chain running. Where are the env files, also how to run the go API and applications etc ?

**Comment by shahthepro** [comment]
I haven’t added build instructions yet. Will do so, if and when time permits.

**Comment by robocrotic** [comment]
Can you share the env files at least ? and explain how to start the golang app ? Ill figure it out eventually but its a little unclear right now what is what as theres multiple apps all in the same repo.

**Comment by robocrotic** [comment]
Happy to help contribute on this if I can get more information, it looks cool and a lot of work has been done so far

**Comment by shahthepro** [comment]
Thank you very much for your interest. Setting up the build for the first time is actually quiet a long process. I'm doing this project in my free time. I'll try to update the readme in a couple of days.

**Comment by shahthepro** [comment]
The wiki page is complete. https://github.com/shahthepro/dex/wiki/Build-Instructions

Closing this issue. Raise a new issue if you are facing any problems during the build process.
